const desserts = [
    "Chocolate Cake",
    "Apple Pie",
    "Cheesecake",
    "Tiramisu",
    "Brownies",
    "Cupcakes",
    "Pavlova",
    "Ice Cream Sundae",
    "Banoffee Pie",
    "Éclair",
    "Creme Brulee",
    "Key Lime Pie",
    "Red Velvet Cake",
    "Strawberry Shortcake",
    "Lemon Meringue Pie",
    "Chocolate Chip Cookies",
    "Raspberry Tart",
    "Panna Cotta",
    "Carrot Cake",
    "Fruit Tart",
    "Pumpkin Pie",
    "Macarons",
    "Baklava",
    "Bread Pudding",
    "Black Forest Cake",
    "Rice Pudding",
    "Trifle",
    "Mousse",
    "Cannoli",
    "Lava Cake",
    "Profiteroles",
    "Scones",
    "Mochi",
    "Fudge",
    "Angel Food Cake",
    "Peach Cobbler",
    "Gelato",
    "Donuts",
    "Pineapple Upside Down Cake",
    "Croissants",
    "Shortbread",
    "S'mores",
    "Churros",
    "Biscotti",
    "Cherry Pie",
    "Coconut Macaroons",
    "Bundt Cake",
    "Napoleon",
    "Madeleines"
  ];

  export default desserts;
  
  